GET http://localhost:8080/api/test
Authorization: Basic admin admin

###
GET http://localhost:8080/api/username
Authorization: Basic jambon jambon

###
GET http://localhost:8080/api/username
Authorization: Basic admin admin

###
GET http://localhost:8080/api/username
Authorization: Basic hacking $2y$12$z0Tr5keihbunVAKAbNEqPOtnxFl1fbw3kV6JMInQtkKgwxA0QYIBa